const CONSTANTS = {
  ORDER_STATUS: 'status',
  PAYMENT_STATUS: 'payment_status',
};

const FILE_SLUGS = {
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub-category',
  PRODUCT: 'product',
};

const FILE_TYPES = {
  IMAGE: 'image',
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PICKED: 'PICKED',
  ON_THE_WAY: 'ON_THE_WAY',
  DELIVERED: 'DELIVERED',
  REQUESTED: 'REQUESTED',
  CANCELLED: 'CANCELLED',
};

const ORDER_PAYMENT_STATUS = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
};

const USER_PAYMENT_STATUS = {
  INITIATED: 'INITIATED',
  REFUNDED: 'REFUNDED',
  CAPTURED: 'CAPTURED',
};

const NOTIFICATION_SLUG = {
  ORDER_REQUESTED: 'ORDER_REQUESTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
};

const USER_TYPE = {
  ADMIN: 'admin',
  USER: 'user',
};

const NOTIFICATION_TYPE = {
  ORDER_REQUEST: 'order_request',
  ORDER_CONFIRM: 'order_confirm',
  ORDER_CANCEL: 'order_cancel',
};

const RESPONSE_TYPE = {
  BLOB: 'BLOB',
  CSV: 'CSV',
};

export {
  CONSTANTS,
  FILE_SLUGS,
  FILE_TYPES,
  ORDER_STATUS,
  ORDER_PAYMENT_STATUS,
  USER_PAYMENT_STATUS,
  NOTIFICATION_SLUG,
  USER_TYPE,
  NOTIFICATION_TYPE,
  RESPONSE_TYPE,
};
