const CONSTANTS = {
  ORDER_STATUS: 'status',
  PAYMENT_STATUS: 'payment_status',
};

const FILE_SLUGS = {
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub-category',
  PRODUCT: 'product',
};

const FILE_TYPES = {
  IMAGE: 'image',
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PICKED: 'PICKED',
  ON_THE_WAY: 'ON_THE_WAY',
  DELIVERED: 'DELIVERED',
  REQUESTED: 'REQUESTED',
  CANCELLED: 'CANCELLED',
};

const ORDER_PAYMENT_STATUS = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
};

const USER_PAYMENT_STATUS = {
  INITIATED: 'INITIATED',
  REFUNDED: 'REFUNDED',
  CAPTURED: 'CAPTURED'
};

export { CONSTANTS, FILE_SLUGS, FILE_TYPES, ORDER_STATUS, ORDER_PAYMENT_STATUS, USER_PAYMENT_STATUS };