export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const IMAGE_REPOSITORY = 'IMAGE_REPOSITORY';
export const SUB_CATEGORY_REPOSITORY = 'SUB_CATEGORY_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const FILE_REPOSITORY = 'FILE_REPOSITORY';
