const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
const IMAGE_REPOSITORY = 'IMAGE_REPOSITORY';
const SUB_CATEGORY_REPOSITORY = 'SUB_CATEGORY_REPOSITORY';
const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
const FILE_REPOSITORY = 'FILE_REPOSITORY';
const PRODUCT_PRICE_REPOSITORY = 'PRODUCT_PRICE_REPOSITORY';
const MEASURING_UNIT_REPOSITORY = 'MEASURING_UNIT_REPOSITORY';
const USER_REPOSITORY = 'USER_REPOSITORY';
const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
const ORDER_PRODUCT_REPOSITORY = 'ORDER_PRODUCT_REPOSITORY';
const USER_PAYMENT_REPOSITORY = 'USER_PAYMENT_REPOSITORY';
const PRODUCT_REVIEW_REPOSITORY = 'PRODUCT_REVIEW_REPOSITORY';
const PRODUCT_REVIEW_FILE_REPOSITORY = 'PRODUCT_REVIEW_FILE_REPOSITORY';
const PRODUCT_HISTORY_REPOSITORY = 'PRODUCT_HISTORY_REPOSITORY';
const WISHLIST_REPOSITORY = 'WISHLIST_REPOSITORY';
const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
const NOTIFICATION_USER_REPOSITORY = 'NOTIFICATION_USER_REPOSITORY';
const NOTIFICATION_TEMPLATE_REPOSITORY = 'NOTIFICATION_TEMPLATE_REPOSITORY';
const PRODUCT_DESCRIPTION_REPOSITORY = 'PRODUCT_DESCRIPTION_REPOSITORY';
const COUNTRIES_REPOSITORY = 'COUNTRIES_REPOSITORY';
const STATES_REPOSITORY = 'STATES_REPOSITORY';

export {
  ADMIN_REPOSITORY,
  CATEGORY_REPOSITORY,
  IMAGE_REPOSITORY,
  SUB_CATEGORY_REPOSITORY,
  PRODUCT_REPOSITORY,
  FILE_REPOSITORY,
  PRODUCT_PRICE_REPOSITORY,
  MEASURING_UNIT_REPOSITORY,
  USER_REPOSITORY,
  ORDER_REPOSITORY,
  ADDRESS_REPOSITORY,
  ORDER_PRODUCT_REPOSITORY,
  USER_PAYMENT_REPOSITORY,
  PRODUCT_REVIEW_REPOSITORY,
  PRODUCT_REVIEW_FILE_REPOSITORY,
  PRODUCT_HISTORY_REPOSITORY,
  WISHLIST_REPOSITORY,
  NOTIFICATION_REPOSITORY,
  NOTIFICATION_USER_REPOSITORY,
  NOTIFICATION_TEMPLATE_REPOSITORY,
  PRODUCT_DESCRIPTION_REPOSITORY,
  COUNTRIES_REPOSITORY,
  STATES_REPOSITORY,
};
